### ISSUE TITLE
All Users see Superhero biographies

### ISSUE THREAD

**Issue by loriculberson** [ycartc/marvelus#3]
As a Guest User,
When I click link ""The Good, The Bad and the Bat Shit Cray Cray", or "Characters"
I see a trading cards of various comic book characters, aligned by their attributes,
And when I hover over the images of the character,
The card flips over and I can read a short bio about the character

(reference: http://www.webofheroes.com/)

**Comment by loriculberson** [comment]
Separate by male and female?

**Comment by mihir787** [comment]
When we click on the characters link we should scroll down to see all the characters not just 9 of them.
